name: "build-test"
on:
  pull_request:
    branches:
      - main

jobs:
  test_something:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      checks: write
    steps:
      - name: "Create a check run"
        uses: actions/github-script@v6
        with:
          debug: ${{ secrets.ACTIONS_STEP_DEBUG || false }}
          script: |
            const conclusion = "${{ github.event.workflow_run.conclusion }}" || "success";
            
            const response = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "my-check-name",
              status: "completed",
              conclusion: conclusion,
              details_url: "https://example.com/sadsadsadasd",
              output: {
                title: "my check title !!!!",
                summary: "my *check* summary",
                text: "my text",
              },
            });

      - name: Create GitHub Check Annotation
        run: |
          CHECK_RUN_ID=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"name": "my-check-name", "status": "completed", "conclusion": "'"$conclusion"'"}' \
            "https://api.github.com/repos/${{ github.repository }}/check-runs" \
            | jq -r .id)
  
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"path": "README.md", "start_line": 1, "end_line": 1, "annotation_level": "notice", "message": "Resumo do SonarQube: '"${{ steps.sonar_results.outputs.sonar_results }}'"}' \
            "https://api.github.com/repos/${{ github.repository }}/check-runs/$CHECK_RUN_ID/annotations"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
