name: "build-test"
on:
  pull_request:
    branches:
      - main

jobs:
  test_something:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      checks: write
    steps:
      - name: "Create a check run"
        uses: actions/github-script@v6
        with:
          debug: ${{ secrets.ACTIONS_STEP_DEBUG || false }}
          script: |
            const conclusion = "${{ github.event.workflow_run.conclusion }}" || "success";
            
            const response = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "my-check-name",
              status: "completed",
              conclusion: conclusion,
              details_url: "https://example.com/sadsadsadasd",
              output: {
                title: "my check title !!!!",
                summary: "my *check* summary",
                text: "my text",
              },
            });
            
            console.log(response.data);
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
