name: "build-test"
on: [push]

jobs:
  test_something:
    runs-on: ubuntu-latest
    steps:
      - name: "Create a check run"
        uses: actions/github-script@v6
        with:
          debug: ${{ secrets.ACTIONS_STEP_DEBUG || false }}
          script: |
              // any JavaScript code can go here, you can use Node JS APIs too.
              // Docs: https://docs.github.com/en/rest/checks/runs#create-a-check-run
              // Rest: https://octokit.github.io/rest.js/v18#checks-create
              await github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head_sha: context.sha,
                name: "my-check-name",
                status: "completed",
                // Careful, code injection can happen.
                conclusion: "${{ github.event.workflow_run.conclusion }}",
                // This is safe, not string interpolation.
                details_url: "sdsad",
                output: {
                  title: "my check title",
                  summary: "my *check* summary",
                  text: "my text",
                },
              });
